.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MAKECHS 1 "May 18, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
makechs \- A program that can be used to create additional translation tables for use by JamNNTPd.
.SH SYNOPSIS
.B makechs \<fromchrs\> \<destchrs\> \<frommap\> [\<destmap\>]
.SH DESCRIPTION
The *.chs files in the "xlat" and "unicode/xlat" directories are character set translation tables in the GoldED+ format. The files were created from mappings files found at this URL:
.TP 
http://www.unicode.org/Public/MAPPINGS/
.TP
Fallback sequences for characters that do not exist in the target charset were taken from Markus Kuhn's transliteration tables found at the URL below:
.TP
http://www.cl.cam.ac.uk/~mgk25/download/transtab.tar.gz
.TP 
If you want to create additional translation tables, you can easily do so using this utility.
.SH OPTIONS
A summary of options is included below:
.TP
.B \<fromchrs\>
The fidonet name of the charset you want to convert from.
.TP
.B \<destchrs\>
The fidonet name of the charset you want to convert to.
.TP
.B \<frommap\>
The Unicode mappings file for the source charset. 
.TP
.B \<destmap\>
The Unicode mappings file for the destination charset. If you don't supply a mappings file, makechs will instead create a chs file that converts the source charset to utf-8.
.TP
The output of makechs is written to the console and needs to be redirected to the desired file.
.SH SEE ALSO
.BR jamnntpd(1).
.br
.SH AUTHOR
makechs was written by <upstream author>.
.PP
This manual page was written by Robert James Clay <jame@rocasa.us>,
for the Debian project (but may be used by others).
